/* eBridge SS7 */

package za.co.ebridge.map.api.service.mobility.subscriberInformation;

import java.io.Serializable;

/**
 *
 GPRSChargingID ::= OCTET STRING (SIZE (4)) -- The Charging ID is a unique four octet value generated by the GGSN when -- a
 * PDP Context is activated. A Charging ID is generated for each activated context. -- The encoding is defined in 3GPP TS
 * 29.060.
 *
 *
 * @author david@tekeshe.com
 *
 */
public interface GPRSChargingID extends Serializable {

    byte[] getData();

}
