package za.co.ebridge.tcap.api.api.tc.dialog.events;

import za.co.ebridge.tcap.api.asn.comp.PAbortCauseType;

/**
 * <pre>
 * -- NOTE � When the Abort Message is generated by the
 * Transaction sublayer, a p-Abort Cause must be
 * -- present.The u-abortCause may be generated by the
 * component sublayer in which case it is an ABRT
 * -- APDU, or by the TC-User in which case it could be
 * either an ABRT APDU or data in some user-defined
 * -- abstract syntax.
 * </pre>
 */
public interface TCPAbortIndication
        extends DialogIndication
{

    // mandatory
    PAbortCauseType getPAbortCause();

    /**
     * If the provider error is generated by the local TCAP Provider returns true If the provider error is generated
     * by the
     * remote TCAP Provider returns false
     *
     * @return
     */
    // boolean isLocalProviderOriginated();

}
