package za.co.ebridge.tcap.api.api.tc.dialog.events;

import za.co.ebridge.tcap.api.asn.AbortSource;
import za.co.ebridge.tcap.api.asn.ApplicationContextName;
import za.co.ebridge.tcap.api.asn.ResultSourceDiagnostic;
import za.co.ebridge.tcap.api.asn.UserInformation;

/**
 * <pre>
 * -- NOTE � When the Abort Message is generated by the
 * Transaction sublayer, a p-Abort Cause must be
 * -- present.The u-abortCause may be generated by the
 * component sublayer in which case it is an ABRT
 * -- APDU, or by the TC-User in which case it could be
 * either an ABRT APDU or data in some user-defined
 * -- abstract syntax.
 * </pre>
 */
public interface TCUserAbortIndication
        extends DialogIndication
{

    /**
     * Returns true if AARE Apdu is included
     *
     * @return
     */
    Boolean IsAareApdu();

    /**
     * Returns true if ABRT Apdu is included
     *
     * @return
     */
    Boolean IsAbrtApdu();

    UserInformation getUserInformation();

    AbortSource getAbortSource();

    ApplicationContextName getApplicationContextName();

    ResultSourceDiagnostic getResultSourceDiagnostic();

}
