package za.co.ebridge.tcap.api.api.tc.dialog.events;

import za.co.ebridge.tcap.api.asn.ApplicationContextName;
import za.co.ebridge.tcap.api.asn.DialogServiceUserType;
import za.co.ebridge.tcap.api.asn.UserInformation;

/**
 * <pre>
 * -- NOTE � When the Abort Message is generated by the Transaction sublayer, a p-Abort Cause must be
 * -- present.The u-abortCause may be generated by the component sublayer in which case it is an ABRT
 * -- APDU, or by the TC-User in which case it could be either an ABRT APDU or data in some user-defined
 * -- abstract syntax.
 * </pre>
 */
public interface TCUserAbortRequest
        extends DialogRequest
{

    void setReturnMessageOnError(boolean val);

    boolean getReturnMessageOnError();

    ApplicationContextName getApplicationContextName();

    void setApplicationContextName(ApplicationContextName acn);

    UserInformation getUserInformation();

    void setUserInformation(UserInformation acn);

    /**
     * Setting of {@link DialogServiceUserType} will create the AARE else ABRT is formed
     *
     * @param dialogServiceUserType
     */
    void setDialogServiceUserType(DialogServiceUserType dialogServiceUserType);

    DialogServiceUserType getDialogServiceUserType();

}
